---
- name: Copy zk_tar_gz to client
  unarchive: src=/etc/ansible/package/zookeeper-3.4.6.tar.gz  dest=/home/hadoop owner=hadoop group=hadoop
  when: status == 'install'

- name: mkdir
  file: path=/home/hadoop/zookeeper-3.4.6/data state=directory owner=hadoop group=hadoop

- name: Setup myid
  template: dest="/home/hadoop/zookeeper-3.4.6/data/myid" src=myid.j2 owner=hadoop group=hadoop

- name: copy start.sh
  copy: dest="/home/hadoop/zookeeper-3.4.6/bin" src=start.sh owner=hadoop group=hadoop mode=0755

- name: copy stop.sh
  copy: dest="/home/hadoop/zookeeper-3.4.6/bin" src=stop.sh owner=hadoop group=hadoop mode=0755

- name: Setup zoo.cfg
  template: dest="/home/hadoop/zookeeper-3.4.6/conf/zoo.cfg" src=zoo.cfg.j2 owner=hadoop group=hadoop
  notify:
   - restart zookeeper


#- name: Setup Apache ZooKeeper service
#  template: dest="/etc/init.d/zookeeper" src=zookeeper mode=0755 owner=hadoop group=hadoop
#  register: zookeeper_service

#- name: chkconfig zookeeper
#  command: chkconfig --add /etc/init.d/zookeeper
#  when: zookeeper_service | changed

#- name: restart zookeeper
#  command: /etc/init.d/zookeeper restart

