---
#注意要修改slaves模板文件
- hosts: hadoop
  remote_user: hadoop
  vars: 
     - javapath: "/opt/jdk1.8.0_111"
     - hadoop_home: "/home/hadoop/hadoop-2.6.0"
     - zookeeper_host_1: "open132"
     - zookeeper_host_2: "open133"
     - zookeeper_host_3: "open134"

     - NameNode1: "open131"
     - NameNode2: "open132"

     - rm1_ip: "172.16.1.131"
     - rm2_ip: "172.16.1.132"
     - status: "install"
  roles:
     - hadoop
