---
#mysql_ip 为hivemysql地址
- hosts: spark
  remote_user: hadoop
  vars: 
     - javapath: "/opt/jdk1.8.0_111"
     - HADOOP_CONF_DIR: "/home/hadoop/hadoop-2.6.0/etc/hadoop"
     - HADOOP_HOME: "/home/hadoop/hadoop-2.6.0"
     - SPARK_MASTER_IP: "bigdata03"

     - zookeeper_host_1: "bigdata01"
     - zookeeper_host_2: "bigdata02"
     - zookeeper_host_3: "bigdata03"

     - NameNode1: "bigdata02"
     - NameNode2: "bigdata03"
     - ResourceManager1: "bigdata02"
     - ResourceManager2: "bigdata03"
     - JournalNode1: "bigdata04"
     - JournalNode2: "bigdata05"
     - JournalNode3: "bigdata06"

     - mysql_ip: "192.168.100.33"


  roles:
     - spark
