---
- hosts: zookeeper
  remote_user: hadoop
  vars: 
     - zookeeper_data_dir: "/home/hadoop/zookeeper-3.4.6/data"
     - zookeeper_log_dir: "/var/log/zookeeper"
     - zookeeper_dir: "/home/hadoop/zookeeper-3.4.6"
     - zookeeper_conf_dir: "/home/hadoop/zookeeper-3.4.6/conf"
     - status: "install"
  roles:
     - zookeeper

